# Generated by Django 2.2.6 on 2019-10-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa_fisica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='pessoa_fisica.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='pessoa_fisica.Pessoa'),
        ),
    ]
